# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saved_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_vid', models.CharField(max_length=500)),
            ],
        ),
    ]
